# Generated by Django 4.2.3 on 2023-07-05 23:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=50)),
                ('bank', models.CharField(choices=[('NU', 'Nubank'), ('CE', 'Caixa Econômica'), ('ITU', 'Itaú Unibanco'), ('C6', 'C6 Bank'), ('INT', 'Banco Inter'), ('BR', 'Bradesco'), ('BB', 'Bando do Brasil')], max_length=3)),
                ('tipo', models.CharField(choices=[('PJ', 'Pessoa Jurídica'), ('PF', 'Pessoa Física')], max_length=2)),
                ('valor', models.FloatField()),
                ('icon', models.ImageField(upload_to='icones')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='essencial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoria',
            name='valor_planejamento',
            field=models.FloatField(default=0),
        ),
    ]
