# Generated by Django 4.2.3 on 2023-07-06 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_conta_categoria_categoria_categoria_essencial_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta',
            old_name='bank',
            new_name='banco',
        ),
        migrations.RenameField(
            model_name='conta',
            old_name='icon',
            new_name='icone',
        ),
    ]
